### ISSUE TITLE
Android wear module missing

### ISSUE THREAD

**Issue by irhs** [denzilferreira/aware-client#1]
I didn't find android-wear module in the repo, but I was able to build the repo by commenting out android-wear module references. Do you have any plans to include the android-wear module in this repo?

Thanks for making it open source.

cheers,
Shrirang

**Comment by denzilferreira** [comment]
The Android Wear package is the same as the phone’s package. We are handling detecting which device it is and adapt the package in runtime to turn off/on features that don’t make sense/are not available on the watch. Simply add a symbolic link of aware-core as aware-wear and it should compile just fine. The manifest merging process takes care of getting the right manifest for the phone and wear packages automatically. When you install AWARE on the phone, it will upload itself to the watch for you.


Best,
Denzil;

**Comment by irhs** [comment]
Ah. Thanks!
