### ISSUE TITLE
Collect Application usage data using  aware library in my own app

### ISSUE THREAD

**Issue by WenchenLi** [denzilferreira/aware-client#10]
Hi,
I want to develop my own app using your library collecting application usage info from users. But I realized aware service should be turned on in accessibility as you suggested in this aware client. How could I achieve this by only using aware library? Thanks.

**Comment by denzilferreira** [comment]
The Applications log only works with an accessibility service. Recently, Google changed the API in Lollipop and we are now unable to record background processes.
