### ISSUE TITLE
Check what esm_status 0 and 2 mean 

### ISSUE THREAD

**Issue by GraceBae** [denzilferreira/aware-client#11]
Make sure we are consistent about how we use them

**Comment by denzilferreira** [comment]
esm_status	INTEGER	the status of the ESM (0-new, 1-dismissed, 2-answered, 3-expired)

- 0 is a temporary state, that the ESM is queue and should be visible to the user when the ESM service processes the queue.
- 2 is given when the user has provided an answer.
