### ISSUE TITLE
Location data not being collected

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#124]
With the latest dev, I had a study with the default config for Location data and only 3 records in average were recorded per hour, skpping several hours:

'061226c7-2cc0-4014-b5ee-658980df43cf', '15th 20h', '1'
'061226c7-2cc0-4014-b5ee-658980df43cf', '16th 00h', '2'
'061226c7-2cc0-4014-b5ee-658980df43cf', '16th 02h', '2'
'061226c7-2cc0-4014-b5ee-658980df43cf', '16th 03h', '2'
'061226c7-2cc0-4014-b5ee-658980df43cf', '16th 05h', '4'
'061226c7-2cc0-4014-b5ee-658980df43cf', '16th 07h', '1'
'061226c7-2cc0-4014-b5ee-658980df43cf', '16th 10h', '3'

**Comment by denzilferreira** [comment]
If using fused location + location native, Google is smart and doesn't record locations if the phone does not move. This is expected.
