### ISSUE TITLE
Lower frequency support for some sensors

### ISSUE THREAD

**Issue by rkdarst** [denzilferreira/aware-client#160]
Hi,

I was playing with sensor frequencies.  In Android >= 2.3 (or 3.0, I've seen both), you should be able to give any microsecond frequency for sensor updates.  But it's just a recommendation, the frequency can be higher (or even lower it seems).  For some sensors like light, millisecond accuracy is not really that useful, at least for our purposes data once a minute would tell us about what the person is doing.

I have tried giving 10x1e6 microseconds, and so on, but Android actually returns data much more often (but only intermittently).  So you can't even reliably set it to something very slow.

Last night, I started adding support for an explicit threshold.  If a point comes in more often than the sampling period, discard it.  This limits us to the actual frequency we want to record. (I checked and this is actually what Purple Robot does).  Should this be by default or a config option(1), and should it be user-visible(2)?

To go along with this, I'm also adding low_frequency_values and low_frequency_readable arrays for the light/barometer/proximity sensors.  These can default to lower frequency sampling (3).  I can also add "very slow", "ultra slow", etc for the other realtime sensors, in case someone wants some data but not real-time (4).

Thoughts?  A PR will be forthcoming. (initial work in CxAalto/aware-client branch low_frequency_sensors)

Thanks,
- Richard

**Comment by denzilferreira** [comment]
This sounds great. Welcome addition as settings visible to the user, both for low and high sampling hardware sensors.
