### ISSUE TITLE
One-click ESMs

### ISSUE THREAD

**Issue by rkdarst** [denzilferreira/aware-client#169]
For some esms (radio buttons, lickert at least), you have to click an answer and then click OK.  If you could just click the answer and then it immediately goes to the next question, that would save half the touches and be a good psychological improvement in speed.

I probably can't do this myself since I am not that good in Android...

**Comment by denzilferreira** [comment]
That is a bad idea. Mainly because users should always be allowed to change their option. Given the small screen space, it is very easy to make a mistake.
