### ISSUE TITLE
MQTT sensor accepts tcp and ssl configuration, but only establishes connection when configured to use ssl.

### ISSUE THREAD

**Issue by WorldofJARcraft** [denzilferreira/aware-client#245]
In com.aware.Mqtt, lines 408 and 409, the Mqtt protocol is determined by it's port number, which I would not consider to be best practice (ports could have been changed by webmaster). Also, you only allow ssl connections.
There is a condition `if (MQTT_PROTOCOL.equalsIgnoreCase("ssl"))`. If it is true, the configured connection will be established. If it is not (port is set to 1883), no connection at all will be established.
You sould at least print a warning to the console.

**Comment by denzilferreira** [comment]
Good catch. We'll fix it.
