### ISSUE TITLE
Unable to resolve dependency when opening Project

### ISSUE THREAD

**Issue by s3and0s** [denzilferreira/aware-client#251]
I ran into this Gradle Build sync error, with unresolved dependencies. When clicking "Open file" under the error message, it brings up build.gradle (module: aware-phone). 

I'm not sure how to resolve and run the build successfully. Please let me know what other information to provide to assist the resolution of this issue. 

![image](https://user-images.githubusercontent.com/43419636/50198401-59069e00-0300-11e9-973c-c85fafe4a85a.png)

Here is the full error message from the failed sync build: 
Unable to resolve dependency for ':aware-phone@debug/compileClasspath': Could not resolve project :com.aware.plugin.device_usage.
Open File
Show Details

Unable to resolve dependency for ':aware-phone@debug/compileClasspath': Could not resolve project :com.aware.plugin.ambient_noise.
Open File
Show Details

Unable to resolve dependency for ':aware-phone@debugAndroidTest/compileClasspath': Could not resolve project :com.aware.plugin.device_usage.
Open File
Show Details

Unable to resolve dependency for ':aware-phone@debugAndroidTest/compileClasspath': Could not resolve project :com.aware.plugin.ambient_noise.
Open File
Show Details

Unable to resolve dependency for ':aware-phone@debugUnitTest/compileClasspath': Could not resolve project :com.aware.plugin.device_usage.
Open File
Show Details

Unable to resolve dependency for ':aware-phone@debugUnitTest/compileClasspath': Could not resolve project :com.aware.plugin.ambient_noise.
Open File
Show Details

Unable to resolve dependency for ':aware-phone@release/compileClasspath': Could not resolve project :com.aware.plugin.device_usage.
Open File
Show Details

Unable to resolve dependency for ':aware-phone@release/compileClasspath': Could not resolve project :com.aware.plugin.ambient_noise.
Open File
Show Details

Unable to resolve dependency for ':aware-phone@releaseUnitTest/compileClasspath': Could not resolve project :com.aware.plugin.device_usage.
Open File
Show Details

Unable to resolve dependency for ':aware-phone@releaseUnitTest/compileClasspath': Could not resolve project :com.aware.plugin.ambient_noise.
Open File
Show Details

**Comment by denzilferreira** [comment]
Mea culpa. I'll fix it!

**Comment by denzilferreira** [comment]
Should be fixed in latest 👍
