### ISSUE TITLE
I cannot sync gradle

### ISSUE THREAD

**Issue by anhmiuhv** [denzilferreira/aware-client#255]
Log: https://gist.github.com/anhmiuhv/4bdf36f16eb2c6774b65a2264cb2d388

Latest Android Studio version
Mac OS X 10.14.2

**Comment by anhmiuhv** [comment]
Sorry my bad, should have use git clone --recursive

**Comment by anhmiuhv** [comment]
Actually I can build the project now and install on the phone but gradle still have errors.

**Comment by denzilferreira** [comment]
I notice you are using OpenJDK. Can you try with Oracle's JDK?

**Comment by anhmiuhv** [comment]
Actually I upgrade to the latest version of gradle and android plugin and android studio today and everything run well
