### ISSUE TITLE
client crashes on Android 9

### ISSUE THREAD

**Issue by chandrasg** [denzilferreira/aware-client#258]
![screenshot_20190224-152730](https://user-images.githubusercontent.com/19346833/53357639-5aee6e00-38fc-11e9-8361-957e83d27511.png)

seems like the accessibility services have changed in Android 9 and the client needs to be updated to reflect the change?

![screenshot_20190225-195003_settings](https://user-images.githubusercontent.com/19346833/53357640-5aee6e00-38fc-11e9-8519-d18bdc49e1a7.png)

**Comment by denzilferreira** [comment]
Fixed in 4.0.811
