### ISSUE TITLE
Data sync notifications

### ISSUE THREAD

**Issue by akuvisur** [denzilferreira/aware-client#264]
Currently on Android 9 I receive notification sounds and vibrations when I am joined to a study and the data sync gets enabled. 

I believe similar function happens when the foreground service notification pops up.

I dont think its intentional that the user gets explicitly notified of these actions, especially in terms of the data sync the constant notification cues can be highly disruptive.

**Comment by denzilferreira** [comment]
There is a setting for the study you can use to disable those under Webservices > Webservice silent

**Comment by akuvisur** [comment]
Could we just have the notifications be there but with no sound or vibration cues?
