### ISSUE TITLE
[wishlist] customize upload notifications with study name

### ISSUE THREAD

**Issue by rkdarst** [denzilferreira/aware-client#27]
Hi,

While testing AWARE, we saw that upload notifications say "AWARE Sync".  For studies where subjects don't know what AWARE is, it could be useful to have the study name, or some more information, in the notification.

A simple option could be to use the configured study_name.  Or, there could be another option that can contain a different text that could be used in cases like that.  Then, at least when notifications appear, the study name is seen.  Of course the app name would stay the same so when looking at system things, you would see that.

Relevant location: WebserviceHelper.java, notifyUser function, line 62+

What do you think?  Any ideas?  We could contribute this, but you can probably do and test much faster.

Thanks,

- Richard

**Comment by denzilferreira** [comment]
Just added support for displaying the app_name string. So the header is according to the app in which AWARE is bundled as a library if a standalone app, otherwise it shows AWARE if using the client.
