### ISSUE TITLE
Unable to join study using URL

### ISSUE THREAD

**Issue by nleo575** [denzilferreira/aware-client#272]
Issue found on build 256.

We were unable to join a study by pasting a URL into the app itself. After clicking activate to turn on data collection, the app brings you back to the home screen with no change. The only way to join the study appears to be using the QR code. 

Issue rating: Minor - 2 out of 5 where 5 is worse.

**Comment by denzilferreira** [comment]
Hey, can you try this sequence:
- put URL
- enable Active on study
- set the settings you want to enable data collection

That should work with the study URL that is provided by the dashboard interface (not the browser URL because it's missing the API key)

**Comment by nleo575** [comment]
@denzilferreira 

Update: Using the latest build (259) I can't join any study using the URL or the QR code. 

I'm getting this error in the app on two different studies and using two different Android phones:
![Screenshot_20191021-153706](https://user-images.githubusercontent.com/38141307/67237305-01056000-f419-11e9-8e46-c6eb36677cec.jpg)

**Comment by nleo575** [comment]
@denzilferreira I just downloaded and tried with build 258 and it doesn't have either URL or QR code issue. So to recap: URL joining issue in 256, No issues in 258, Both URL & QR issue in 259.
