### ISSUE TITLE
Aware Client on Samsung Galaxy S8

### ISSUE THREAD

**Issue by spirit2343** [denzilferreira/aware-client#279]
Hello,

We successfully installed Aware 4.0.817 but we werent able to enroll in a study

![Image from iOS (4)](https://user-images.githubusercontent.com/6290258/67609715-03cac280-f743-11e9-8211-6ce4d4f4449a.jpg)
![Image from iOS (5)](https://user-images.githubusercontent.com/6290258/67609716-04fbef80-f743-11e9-8c4a-ca955a1726df.jpg)
![Image from iOS (6)](https://user-images.githubusercontent.com/6290258/67609717-06c5b300-f743-11e9-9774-b66f55857736.jpg)

**Comment by denzilferreira** [comment]
Fixed in latest release.
