### ISSUE TITLE
[bug] UI not updated after configuration URL entered

### ISSUE THREAD

**Issue by rkdarst** [denzilferreira/aware-client#28]
Hi,

While QR was crashing my app, I was entering the configuration URL manually.  I eventually realized that the following would happen:

- Enter configuration URL
- Go look at options.  You see old config options.
- Exit app by clicking back button repeatedly.  (not just switching to home screen)
- Start app again.  Look at config options, and the configuration retrieved from the server is now show.

I'm not sure if the same happens when configuring via QR code.  

What do you think?  We're not very familiar with the code yet so it may be easiest for you to find, if it's worth it.

Thanks,

- Richard

**Comment by denzilferreira** [comment]
Fixed in latest.

**Comment by rkdarst** [comment]
thanks!
