### ISSUE TITLE
Aware Client Samsung-SM0J129A

### ISSUE THREAD

**Issue by spirit2343** [denzilferreira/aware-client#280]
Hello,

We werent successful installing Build 260 on Samsung-SM0J129A

![Image from iOS (9)](https://user-images.githubusercontent.com/6290258/67609810-90758080-f743-11e9-95e9-ad9885eb10ba.jpg)
![Image from iOS (8)](https://user-images.githubusercontent.com/6290258/67609811-90758080-f743-11e9-84d4-c4bc20e4181b.jpg)
![Image from iOS (7)](https://user-images.githubusercontent.com/6290258/67609812-90758080-f743-11e9-8905-40339bf8efb3.jpg)

**Comment by denzilferreira** [comment]
Android 7+
