### ISSUE TITLE
Screen sensor doesn't record all status changes

### ISSUE THREAD

**Issue by nleo575** [denzilferreira/aware-client#282]
During a review of data we have noticed that the sensor isn't accurately recording all changes in screen_status. For example we have noticed two or more consecutive unlocks without a lock or off in between or vice versa. Some of these are due to duplicated entires in the screen table, others though have different timestamps and are indeed errors. 

The error also seems to be present on iOS.

**Comment by nleo575** [comment]
Our test was using build AWARE build 256 from Jenkins. In what version of the client did you implement this fix?

**Comment by denzilferreira** [comment]
Forgot to set Jenkins to build. Building, this would be build 262.

# Denzil;
