### ISSUE TITLE
Displaying Toast notification and activity when using study link

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#290]
After using a link to join a study (`aware-ssl://`), a toast notification saying `AWARE: Please install this plugin` is shown, followed up by a dialogue message saying `To view this content, install and set up a web browsing app`. After pressing OK  the Plugin activity is shown empty.

**Comment by denzilferreira** [comment]
- fixed in commit 504a7b4a91d0d52dce7f79502cf7e79652dac4e8
