### ISSUE TITLE
[WEB API] The calendar does not allow for changing months

### ISSUE THREAD

**Issue by sbobek** [denzilferreira/aware-client#3]
I have in my database data from year ago. There was a few months break in collecting data, and now we continue. However, the calendar on the website api.awareframework.com does not allow me to go back to previous months. Is it a bug or feature? :)

**Comment by denzilferreira** [comment]
I would say it’s a limitation of the dashboard. We’ll add it to the list of improvements to do.


Thanks!
Denzil;

**Comment by denzilferreira** [comment]
New dashboard is being implemented, allowing to go back in time.
