### ISSUE TITLE
Bluetooth beacon support

### ISSUE THREAD

**Issue by rkdarst** [denzilferreira/aware-client#35]
Hi,

We'd like to add support for bluetooth beacons.  I opened a issue at CxAalto/aware-client#3 which we will use for discussion.  Would you like to comment there (or here)?  Mainly we should settle on a client-server API for configuration, and then DB schema.

Thanks
- Richard

**Comment by akuvisur** [comment]
Hi Richard,

I know there has been work on changing the core bluetooth sensor but you might also take a look at 
https://github.com/akuvisur/bluetooth_beacon_detect

It is using the android beacon detect library to scan for nearby beacons.

**Comment by denzilferreira** [comment]
We have also now support on Bluetooth scanning for BLE devices.
