### ISSUE TITLE
[Wishlist] Add support for sensing scheduling

### ISSUE THREAD

**Issue by denzilferreira** [denzilferreira/aware-client#36]
> Is there any way (or will there be in the future…) to schedule when data is logged? For instance, I would only like to log data between the hours of 4pm and 1am. Having certain options enabled really seems to drain the battery and use data necessarily, so it would be nice to be able to stop this when not required.

**Comment by rkdarst** [comment]
I was thinking about this and it would be nice to have.  I think I have a strategy for doing this which isn't that hard and maybe within my skill level.

- There is some way for a schedule to turn on a sensor.  Does this already exist?
- There is an option for a sensor to turn itself off after a certain time has elapsed.  This can be a simple check in the onSensorChanged handler.
- The time threshold can be sent different ways.  For example, it could be a direct config option, or an extra from the scheduler.
- And I guess there should be some sort of fallback.  Does it default to on, unless a schedule is made?  or default to off?

What do you think?  Is there a better way?

Also, I was wondering about risk of the scheduler service stopping, or a schedule getting corrupted, or ....  If it stopped, is all lost (no data collected, no data synced)?  I guess in this case probably Aware isn't running and it can't collect any data anyway, so it's not a concern.  Is there any way to be defensive about this?

Thanks,
- Richard

**Comment by denzilferreira** [comment]
We will use WorkManager to schedule and handle the sampling strategies in newer kotlin library.
