### ISSUE TITLE
If user already in study, using QR code does not change their study.

### ISSUE THREAD

**Issue by rkdarst** [denzilferreira/aware-client#66]
Steps to reproduce:
- Link study via QR code
- Observe that you are in a study
- While still in that study, scan a QR code for a different study.
- webservice_server does not change, and also if you click the study icon, it presents information on the first study, not the second.

I just found this with a tester (@TuomasA) here, I haven't looked into it yet.

- Richard

**Comment by denzilferreira** [comment]
Can't replicate on the latest master source.

**Comment by rkdarst** [comment]
At least appears to work for me now (changes active sensors).
