### ISSUE TITLE
7.0 Applications_foreground doesn't detect changes when hiding notification bar

### ISSUE THREAD

**Issue by akuvisur** [denzilferreira/aware-client#78]
The notification bar is detected as a different application package when the bar is opened by swiping down on the top of the screen, and the sensor logs the foreground application change as normal. However, when the bar is hidden by swiping upwards, the change of foreground application is not detected for some applications, such as the home screen (com.google.android.googlequicksearchbox).

**Comment by denzilferreira** [comment]
This is normal behavior.
