### ISSUE TITLE
Storing client data on external storage

### ISSUE THREAD

**Issue by rkdarst** [denzilferreira/aware-client#89]
Hi,

At one point, we had discussed possibility for storing data on external app storage.  If I rememember right, this should be doable now.  I see that DatabaseHelper.getAwareDatabaseDirectory has a conditional to use the internal storage.  Can this be configured via json, or some means, without.

Also, I was thinking: if the problem is that plugins wouldn't be able to use the same device ID: how big of a problem is this?  If all uploads are done via the main app WebserviceHelper, it should be able to know the authorative device_id, and could replace it with the right one.  (in my case, my server can ignore device IDs since it is all encoded within the the upload URL).

This is more advisory, to ask what the status of using internal storage is.  Does it require a standalone app?  Do plugins work?  Could we make some way to enable this by the server JSON config?

Thanks,

- Richard

**Comment by denzilferreira** [comment]
Hi Richard,

There is now a parameter you can set on your branch that makes the client and plugins store their data on the Android/data folders: it's a xml bool called standalone. Set that to true on your package, and it's going to use the app storage instead of the shared folder.

Best,
D;
